const baground = document.getElementById('bod2')
const options = document.querySelector(".opti")
const options1 = document.querySelector(".opti1")
const options2 = document.querySelector(".opti2")
var state = localStorage.getItem('state')
const form = document.querySelector(".form")
const logo = document.getElementById("logo")
var short = document.getElementById("short-btn")
var copy = document.getElementById("copy-btn")
var footer = document.getElementById("foot")
var foot = document.querySelector(".foot")
var f1 = document.getElementById("f1")
var f2 = document.getElementById("f2")
var f3 = document.getElementById("f3")
var f4 = document.getElementById("f4")
var f5 = document.getElementById("f5")
var f6 = document.getElementById("f6")
var f7 = document.getElementById("f7")
var f8 = document.getElementById("f8")
var copy2 = document.getElementById("copy")
if (state=='darkmode'){
    baground.style.backgroundColor='black'
    options.style.color='white'
    options1.style.color='white'
    options2.style.color='white'
    logo.style.color='white'
    form.style.backgroundColor='#BFBFBF'
    short.style.backgroundColor='#999999'
    copy.style.backgroundColor='#999999'
    footer.style.backgroundColor='black'
    foot.style.color='white'
    f1.style.color='white'
    f2.style.color='white'
    f3.style.color='white'
    f4.style.color='white'
    f5.style.color='white'
    f6.style.color='white'
    f7.style.color='white'
    f8.style.color='white'
    copy2.style.color='white'
} else{
    baground.style.backgroundColor='#E0EEC2'
    options.style.color='black'
    options1.style.color='black'
    options2.style.color='black'
    logo.style.color='black'
    short.style.backgroundColor='#A0B288'
    copy.style.backgroundColor='#A0B288'
    footer.style.backgroundColor='#E0EEC2'
    foot.style.color='black'
    f1.style.color='black'
    f2.style.color='black'
    f3.style.color='black'
    f4.style.color='black'
    f5.style.color='black'
    f6.style.color='black'
    f7.style.color='black'
    f8.style.color='black'
    copy2.style.color='black'
}